// Tabby as pixel art, for terminals that draw pictures (kitty, Ghostty).
// Generated; 16x14 RGBA PNGs, base64.
export const CAT_PNG: Record<'happy' | 'sleep' | 'sad' | 'work', string> = {
  happy: 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAOCAYAAAAmL5yKAAAAaElEQVR42mNggIJpbkb/GYgEGGpBAjfLw/8TYwhWtTBBQobgVIcsAZPEhtHVYNVMCgYbQlUDNOTkwBiXBnR56rsAHX+YtgCM8RpAbkBiTUzEGARTRzChEG0zvmSKbBtRyR3deYT4IAAAK7eHEvO32yMAAAAASUVORK5CYII=',
  sleep: 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAOCAYAAAAmL5yKAAAAYElEQVR42mNggIJpbkb/GYgEGGpBAjfLw/8TYwhWtTBBQobgVIcsAZPEhtHVYNVMCgYbQlUDsDkVm9do5wJCNmI1gNyAxJqYiDEIpo5gQiHaZnzJFNk2opI7uvMI8UEAAC6Fh4q+Ajm1AAAAAElFTkSuQmCC',
  sad: 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAOCAYAAAAmL5yKAAAAZElEQVR42mNggIJpbkb/GYgEGGpBAjfLw/8TYwhWtTBBQobgVIcsAZPEhtHVYNVMCgYbQlUDNOTk/oMALg3o8tR3ATYFhOTJDkisiYkYg2DqCCYUom3Gl0yRbSMquaM7jxAfBAD58YoU0h+6qQAAAABJRU5ErkJggg==',
  work: 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAOCAYAAAAmL5yKAAAAaElEQVR42mNggIJpbkb/GYgEGGpBAjfLw/8TYwhWtTBBQobgVIcsAZPEhtHVYNVMCgYbQlUDQEBDTg6nBnR56rsAHX+YtgCM8RpAbkBiTUzEGARTRzChEG0zvmSKbBtRyR3deYT4IAAAHe2MRL1W4nIAAAAASUVORK5CYII=',
}
